exclude: ^(venv/|.venv/env/|.env/|version.txt)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
        - id: isort
          args: ["--line-length=97", "--profile=black"]

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
        - id: black
          args: ["--line-length=97", "--target-version=py39"]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=97", "--ignore=E402"]
